name: Run Cypress Tests

on:
  push:
    branches:
      - main 
  pull_request: 

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18 

    # Install dependencies
    - name: Install dependencies
      run: npm install

    # Install Cypress
    - name: Install Cypress
      run: npm install cypress --save-dev

    # Run Cypress tests
    - name: Run Cypress Tests
      run: npx cypress run

    # Save Cypress videos and screenshots for debugging (optional)
    - name: Upload test artifacts
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: cypress-artifacts
        path: cypress/videos
